# services:
#   app:
#     container_name: "plimp"
#     image: "plimp:latest"
#     build:
#       context: .
#     restart: always
#     env_file:
#       - .env
#     ports:
#       - 8000:8000
#     volumes:
#       - ./data:/app/data

services:
  migration:
    build:
      context: .
    command: alembic upgrade head
    restart: always
    env_file:
      - .env
    environment:
    - DB_CONNECTION_URL=postgresql+psycopg2://postgres:postgres@plimp-db-1:5432/plimp_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data
  db:
    image: postgres
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=plimp_db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=plimp-db-1
      - ADMINER_DEFAULT_USERNAME=postgres
      - ADMINER_DEFAULT_DATABASE=plimp_db
volumes:
  db-data: